{{- if .Values.auth.tlsEnabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ironic-cacert
spec:
  commonName: ironic-ca
  isCA: true
  ipAddresses:
  - {{ .Values.services.ironic.ironicIP }}
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: ironic-cacert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ironic-cert
spec:
  commonName: ironic-cert
  ipAddresses:
  - {{ .Values.services.ironic.ironicIP }}
  issuerRef:
    kind: Issuer
    name: ca-issuer
  secretName: ironic-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ironic-inspector-cert
spec:
  commonName: ironic-inspector-cert
  ipAddresses:
  - {{ .Values.services.ironic.ironicIP }}
  issuerRef:
    kind: Issuer
    name: ca-issuer
  secretName: ironic-inspector-cert
{{- end }}
