apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: baremetal-operator-serving-cert
spec:
  dnsNames:
  - baremetal-operator-webhook-service.{{ .Release.Namespace }}.svc
  - baremetal-operator-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: baremetal-operator-selfsigned-issuer
  secretName: bmo-webhook-server-cert
