apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ironic-shared-volume
spec:
  accessModes:
  - {{ .Values.persistence.ironic.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.ironic.size }}
  {{- if or .Values.global.storageClass .Values.persistence.ironic.storageClass }}
  storageClassName: {{ .Values.global.storageClass | default .Values.persistence.ironic.storageClass }}
  {{- end }}
  volumeMode: Filesystem
