apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: baremetal-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: baremetal-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "metal3.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
