apiVersion: v1
data:
  password: {{ .Values.mariadb.auth.ironicPassword | b64enc }}
kind: Secret
metadata:
  name: mariadb-password
type: Opaque
{{- if .Values.auth.basicAuthEnabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ironic-auth-config
data:
  auth-config: |
    {{ tpl (.Files.Get "ironic-scripts/ironic-auth-config") . | b64enc | nindent 4 }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: ironic-inspector-auth-config
data:
  auth-config: |
    {{ tpl (.Files.Get "ironic-scripts/ironic-inspector-auth-config") . | b64enc | nindent 4 }}
type: Opaque
{{- end }}
