{{- if .Values.auth.basicAuthEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ironic-credentials
data:
  username: {{ .Values.auth.ironicUsername | b64enc }}
  password: {{ .Values.auth.ironicPassword | b64enc }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: ironic-inspector-credentials
data:
  username: {{ .Values.auth.ironicInspectorUsername | b64enc }}
  password: {{ .Values.auth.ironicInspectorPassword | b64enc }}
type: Opaque
{{- end }}
