apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: baremetal-operator-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  name: baremetal-operator-webhook-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: controller-manager
    webhook: metal3-io-v1alpha1-baremetalhost
